### PR TITLE
Restore JDK8 support

### LINKED ISSUE #127: Classes are compiled with Java 11
On the github page is states that the library _Works with all relevant Java versions: 1.8 and 1.11 - using JUnit 4.13.1 (4.11 does not work) or JUnit 5_ but when i include version 1.0.0 in a Java 8 project, i get the error

```
.../BaseProcessTest.java:29: error: cannot access org.camunda.bpm.extension.process_test_coverage.junit.rules.MinimalCoverageMatcher
import org.camunda.bpm.extension.process_test_coverage.junit.rules.MinimalCoverageMatcher;
                                                                  ^
  bad class file: [sni]/org.camunda.bpm.extension/camunda-bpm-process-test-coverage-junit4/1.0.0/a12941963e854c29ec524fb03d1788dc6d022152/camunda-bpm-process-test-coverage-junit4-1.0.0.jar(org/camunda/bpm/extension/process_test_coverage/junit/rules/MinimalCoverageMatcher.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

i assume the culprit is this entry in the pom.xml https://github.com/camunda-community-hub/camunda-bpm-process-test-coverage/blob/master/pom.xml#L26

If Java 8 should still be supported, then this needs to be fixed.

### PR DESCRIPTION
**Pull request by zambrovski**
* restored support of Java 8
* made CoverageUtil more stable*
* bumped some deps
* fix #127

### CODE REVIEW

**Comment by ingorichtsmeier** [comment]
Hi @zambrovski, it seems that we both spend the evening on the same topic. 

And got (nearly) the same results: https://github.com/camunda-community-hub/camunda-bpm-process-test-coverage/pull/172

**Comment by zambrovski** [comment]
I'll extend the compatibility check for the legacy support to run on JDK 8
